### ISSUE TITLE
关于永久图文素材相关接口下线的公告

### ISSUE THREAD

**Issue by awebc** [jianyan74/rageframe3#1]
https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&announce_id=11644831863qFQSh&version=&lang=zh_CN

**rageFrame框架微信图文素材功能和微信API不符合了，请知悉！**

因图文素材已升级为草稿箱，公众平台将于2022年2月28日下线永久图文素材相关接口。届时，开发者将无法通过接口新增永久图文素材。已经生成的永久图文素材仍可以访问、获取和删除，但无法修改。为避免影响使用，请开发者使用草稿箱（[草稿箱接口文档](https://developers.weixin.qq.com/doc/offiaccount/Draft_Box/Add_draft.html) ）和内容发布接口（ [发布能力接口文档](https://developers.weixin.qq.com/doc/offiaccount/Publish/Publish.html)）生成和获取文章链接。

受此次影响的永久图文素材接口包括：

[新增永久图文素材接口](https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Adding_Permanent_Assets.html)：下线后，无法通过此接口创建新的永久图文素材。

[修改永久图文素材接口](https://developers.weixin.qq.com/doc/offiaccount/Asset_Management/Editing_Permanent_Rich_Media_Assets.html)：下线后，无法通过此接口修改已有的永久图文素材。

上述接口下线时间为2022年2月28日，请开发者尽快调整相关接口，避免影响使用。如有疑问，可前往[[微信开放社区-公众号专区](https://developers.weixin.qq.com/community/minihome/question/1277775808983138305)]反馈。

**Comment by jianyan74** [comment]
ok 下个版本修改

**Comment by jianyan74** [comment]
已修复
