### ISSUE TITLE
我都配置好了，这个页面对吗？

### ISSUE THREAD

**Issue by Eberron91** [jianyan74/rageframe3#8]
我是都按照安装要求来的，配置数据库 ，和安装依赖都没有任何问题，目录也指向了当前项目的web下，
但是打开是这样页面
![0](https://github.com/jianyan74/rageframe3/assets/42966631/d75e9934-b7f0-4bd9-a72c-71a1ac3b6f36)

**Comment by Eberron91** [comment]
但是 web/backend 下的index.php似乎能正确进入页面，这是什么问题，我看了web/backend 下的index.php代码和web下的index.php的代码是一样的
![1 ] (https://github.com/jianyan74/rageframe3/assets/42966631/218ba804-cd1f-478a-95ca-6b3784259fdf)

**Comment by Eberron91** [comment]
但是 web/backend 下的index.php似乎能正确进入页面，这是什么问题，我看了web/backend 下的index.php代码和web下的index.php的代码是一样的
![1](https://github.com/jianyan74/rageframe3/assets/42966631/82402fe9-d91b-4e68-9908-c018061e4e40)

**Comment by jianyan74** [comment]
这个是正确的
